# Generated by Django 5.1.2 on 2024-10-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('time_complexity', models.CharField(max_length=100)),
                ('space_complexity', models.CharField(max_length=100)),
            ],
        ),
    ]
